### PR TITLE
Remove snappy from applications, update README

### LINKED ISSUE #37: Snappy not resolving as a dependency
With a new project and

```
  def application do
    [applications: [:logger, :kafka_ex]]
  end

  defp deps do
    [{:kafka_ex, "~> 0.2"}]
  end
end
```

in the `mix.exs` file, I do a `mix deps.get`, `mix deps.compile`, and `iex` fails with

```
** (Mix) Could not start application snappy: could not find application file: snappy.app
```

Inspection of `mix.lock` shows that snappy was not resolved as a dependency.

I'm not sure why this is happening - I put snappy in the KafkaEx `mix.exs`.  Manually adding snappy as a dependency to the downstream project should resolve it in an emergency, but this should be fixed :(

### PR DESCRIPTION
**Pull request by dantswain**
Should close #37.

### CODE REVIEW

**Comment by dantswain** [comment]
@bjhaid you may want to push a hotfix to hex after this.  0.2.0 will fail in the wild unless the user adds snappy to their mix.exs :(

**Comment by bjhaid** [comment]
@dantswain thanks for this, but it would be great if you can include an example of how to add it to the `mix.exs` file

**Comment by dantswain** [comment]
Sorry @bjhaid I got bogged down for the last two weeks with ElixirConf and work travel.  Thanks for updating!

**Comment by bjhaid** [comment]
that's fine, thanks for the work :heart:

**Pull request closed without merging**
