### PR TITLE
Fix JoinGroup Serialization

### PR DESCRIPTION
**Pull request by dcuddeback**
This PR fixes the serialization errors described in #158 and #159.

### CODE REVIEW

**Comment by bjhaid** [comment]
@cdegroot please do review thanks!

**Comment by dantswain** [comment]
Did the spec change?  That's my main concern.

**Comment by cdegroot** [comment]
@dantswain if you meant the Kafka spec, no. That spec is actually very well-versioned. I typed in most of the serialization code in one go, with in the back of my mind that it doesn't really matter too much whether it's correct _unless_ we want to aim for 100% compatibility with the Java client. So @dcuddeback is just fixing my mistakes here, most likely ;-).

**Comment by cdegroot** [comment]
PR is cleanup and adding a missing byte size field, which is in line with the spec for `ProtocolMetadata` (specified as `bytes` so it needs a size). :shipit:

**Pull request merged**
