### PR TITLE
modify brokers parsing to allow runtime variables

### PR DESCRIPTION
**Pull request by jruhland**
Added a parser for {:system, NAME} that allows brokers to be passed in at runtime, using standard elixir pattern for managing this.

### CODE REVIEW

**Comment by joshuawscott** [comment]
Actually, looking a bit more, it doesn't seem like `{:system, variable}` is really a standard. Could this be accomplished by using the change in https://github.com/kafkaex/kafka_ex/pull/303 to load the environment variable at runtime?

**Comment by greenboxal** [comment]
@joshuawscott it could but, they're not mutually exclusive. it's not really a standard but a lot of Elixir libraries follow this pattern (including Ecto and Phoenix).

I would say that for 99% of people this option works better than #303 because it's less boilerplate.

**Comment by dantswain** [comment]
@greenboxal FYI Ecto no longer supports this format: https://hexdocs.pm/ecto/Ecto.Repo.html#module-urls

Personally I think the "right" solution is for KafkaEx to support something like the init callback.  I think this is entirely possible now though it might not be very intuitive.

**Comment by greenboxal** [comment]
@dantswain interesting... do you to what format they're migrating now? are people starting to rely o something like distillery config providers?

**Comment by dantswain** [comment]
The docs have their recommended approach, which I think is a nice solution to the problem.  It's very flexible.

I do recommend using distillery if you can.  In the past we've also used distillery to generate a release and then had our configuration management system overwrite the sys.config that distillery generates.  That might not solve the problem if you need to get config from a service discovery tool, though.  The most flexible approach is what Ecto is recommending now, which basically gives you the flexibility to supply the config however you want.  I believe KafkaEx should be compatible with that sort of approach though I'm a bit overloaded at the moment so I couldn't do the legwork to tell you exactly how :(

**Comment by greenboxal** [comment]
@dantswain no worries! it makes sense. and actually, with distillery 2 they have pluggable configuration providers, which means that we can get data from the env or svc discovery. definitely considering using it with docker now

anyway, if everyone is moving towards that pattern, I'm ok with it.

**Comment by jruhland** [comment]
ill go head and close this

**Pull request closed without merging**
