### PR TITLE
Fix some integration/consumer group test issues

### PR DESCRIPTION
**Pull request by dantswain**
I think a lot of these problems are due to the asynchronous nature of the code and Kafka.

@bjhaid This isn't ready to merge yet.  I'm creating a PR so that travis will run.  I'm hoping that if I can fix some of these issues, it will help isolate any potential issues in #78

### CODE REVIEW

**Comment by ibizaman** [comment]
You must pay attention with logging. A lot of async issues just vanished when I used it because it added enough delays to resolve them. :/

**Comment by dantswain** [comment]
@ibizaman You are totally correct.  I would say, though, if anything here gets fixed by adding logging, then it was a bug to begin with ;)  So far most of the changes I've made are just trying to get clues as to what the actual underlying problem is.

**Comment by dantswain** [comment]
@bjhaid I managed to get travis set up for my fork, so I can trigger my own rebuilds if I need to.  If you'd prefer, I can close this PR until it is ready for review.  OTOH, leaving it open gives me an extra set of output for debugging.  Either way is fine with me.

**Comment by bjhaid** [comment]
I'll leave it open and I'll look at it later today, sorry didn't respond over the weekend -> I had a busy weekend

**Pull request merged**
