### PR TITLE
Make elixir handle kafka daemons

### PR DESCRIPTION
**Pull request by ibizaman**
Instead of using the install_script to launch the kafka daemons with nearly hardcoded values, now they are launched from the tests themselves and can be configured for the tests.
It should close issue #60 although it is not ready yet.

### CODE REVIEW

**Comment by bjhaid** [comment]
I am slightly worried that this is a lot of non-unit-tested code to spin up test dependencies. While kafka is a required dependency I do not intend to tie spinning of up of kafka to the test code, it takes away freedom from whoever wants to spin up kafka in a different manner to run tests.

If we are to replace the scripts, I will prefer mix task(s) that just shell out do about the same thing the current  set of scripts do.

**Comment by ibizaman** [comment]
Okay, that seems nice too.

In tests I want to write for my application, I need to delete a topic and create it anew. How would you do that having mix tasks?

**Comment by bjhaid** [comment]
Sorry took me a while to respond, the kafka API does not expose any means to deleting topics, but [google search](https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=delete%20kafka%20topic) shows there might be tricks to deleting kafka topics

**Comment by bjhaid** [comment]
Closing this based on discussion on https://github.com/kafkaex/kafka_ex/issues/60

**Pull request closed without merging**
