### PR TITLE
Add describe consumer group request

### PR DESCRIPTION
**Pull request by Argonus**
# Overview
Add describe group request to fetch detailed info about consumer group status.

### CODE REVIEW

**Comment by Argonus** [comment]
@joshuawscott / @dantswain

We are using `kafka_ex` quite heavily in Fresha. And I'd like to help with releasing v1.0.0 of kafka_ex based on kayrock only. But I do not fully understand strategy.
If I'm correct, we should migrate everything that is implemented in the `kafka_ex.ex` file into `kafka_ex_api.ex` & add an adapter that will be able to translate it

**Comment by dantswain** [comment]
Hi @Argonus !  Sorry, I'm trying to catch up here.  Why did you close/delete this PR?

I'd love to have help getting to 1.0.  A big thing that's been in the way for me is that I got a new job and had a couple kids so I haven't had nearly as much time for kafkaex.

**Comment by Argonus** [comment]
Hi @dantswain yeah I've closed is as we are testing describe groups right now internaly and it was creating a bit of mess in our branches. 
Once we verify it I'd happily go back to you with full PR and talk how we can help with v1.0.0 release ;)

**Comment by dantswain** [comment]
Sounds good!

**Pull request closed without merging**
