### PR TITLE
Allow to pass uris as parameters to the ConsumerGroup

### PR DESCRIPTION
**Pull request by MiLk**
You can now load the broker list from the environment and do something like:
```elixir
brokers = [
  {System.get_env("KAFKA_HOST"), String.to_integer(System.get_env("KAFKA_PORT"))},
]

children = [
  supervisor(KafkaEx.ConsumerGroup, [
    gen_consumer_impl,
    consumer_group_name,
    topic_names,
    [uris: brokers]
  ])
]
Supervisor.start_link(children, strategy: :one_for_one)
```

### CODE REVIEW

**Comment by MiLk** [comment]
One of the test timed out, but it now seems to be passing.

**Comment by dantswain** [comment]
@MiLk Thanks!  Could you please also address the ebert notifications?  Looks like just a couple long lines.

I'm hopefully going to be doing a release in the next few days, if we get this smoothed out your PR will be in it :)

**Comment by MiLk** [comment]
For some reason, I didn't see the inline comments from Ebert. Should be good now!

**Comment by dantswain** [comment]
Thanks, @MiLk!

**Comment by bjhaid** [comment]
I was 21 seconds late on clicking approve thanks @MiLk

**Pull request merged**
