### PR TITLE
Allow disabling the default worker, update README and document config.exs

### PR DESCRIPTION
**Pull request by dantswain**
The motivation to disable the default worker is described in #68

I updated the README to point to config/config.exs for the application
env, and updated config/config.exs with comments describing how to use
each of the supported env settings.  I think this makes it easier to
keep everything up-to-date.

### CODE REVIEW

**Comment by bjhaid** [comment]
I suggest this be 2 different PRs one for the config update and the other to enable removing the defauilt_worker, since they are sort of separate concerns, but it looks great, though I will suggest you have a spec that is not run in parallel to update application config with `disable_default_worker: true` and one verifying the default behaviour, otherwise I am :+1:

**Comment by dantswain** [comment]
I figured they were small enough changes it wouldn't be a big deal - I had started to update the README for `disable_default_worker` and kind of said "screw it".

I'll take a stab at writing a test.  It should be possible to stop the app, set the env var, start it, make sure the supervisor has no child processes, then put everything back the way it was.

**Comment by bjhaid** [comment]
I don't think you can stop the app, you can mutate the application config with [`Application.put_env`](http://elixir-lang.org/docs/v1.0/elixir/Application.html#put_env/4) but this will leave it modified, so the test cannot run in parallel and you have to ensure the test cleans up after itself

**Comment by dantswain** [comment]
You _can_ stop the app ;)  See the added test.

**Comment by dantswain** [comment]
Maybe Travis is going to prove me wrong.  I've definitely done this before with other projects.  I'm trying to reproduce the failures locally.

**Comment by dantswain** [comment]
@bjhaid Did you trigger a rebuild?  I couldn't reproduce the failures locally using the same random seed.

**Comment by bjhaid** [comment]
I triggered a rebuild

**Comment by bjhaid** [comment]
So I have been able to make it fail again on travis, I will look at this more closely later today

**Comment by bjhaid** [comment]
I think this spec should run completely independently, so you should give it a `moduletag` and include the tag in this [proplist](https://github.com/kafkaex/kafka_ex/blob/master/test/test_helper.exs#L3), then we can run the spec as `mix test --include integration --include consumer_group; mix test --include integration --include consumer_group && mix test test/kafka_ex_test.exs` and you should update [travis](https://github.com/kafkaex/kafka_ex/blob/master/.travis.yml#L8)

**Comment by dantswain** [comment]
@bjhaid I will do that if you require it, but I really don't think it would help.   I don't think ExUnit sandboxes the tagged modules or anything - running `mix test --include integration --include consumer_group` doesn't do anything different than removing the tags and just running `mix test` AFAIK.   I've used application restarts a bunch of times in the past to test this kind of thing.  Can you tell me what your concerns are?  

I _did_ introduce some test failures when I added the sync_timeout value to config.exs (it was assuming `Application.get_env(:kafka_ex, :sync_timeout)` would return nil).  Those are fixed in the most recent commit.

**Comment by bjhaid** [comment]
my suggestion is to run it as an isolated OS process and not rely on exunit to sandbox it (see the `&&`). My concerns was around Application restart and another spec running in parallel while the application is being restarted, I am not sure if `async: false` is per spec-file or takes effect globally. If `async: false` is global then it should be fine, I will try merging/rebasing against master and running it locally.

**Pull request merged**
