### PR TITLE
Ensure consistency around inflix operators closes #113.

### LINKED ISSUE #113: Ensure consistency of spaces around infix operators

### PR DESCRIPTION
**Pull request by bjhaid**

### CODE REVIEW

**Comment by dantswain** [comment]
I believe this is a bug in credo: https://github.com/rrrene/credo/issues/45

**Comment by bjhaid** [comment]
Not all of it ;) though there's a unary operator bug [here](https://github.com/kafkaex/kafka_ex/blob/72ffaeb6150fe3646d700e384fcae206a0edb410/lib/kafka_ex/protocol.ex#L97)

**Comment by dantswain** [comment]
I think all of the pattern matching stuff is a bug, e.g., `<< valsize :: 32 - unsigned `  _should_ be `<< valsize :: 32-unsigned `.  The credo maintainer confirms - he reopened the issue I referenced above.

The Elixir docs have the bit syntax without spaces around the dashes, too: http://elixir-lang.org/docs/stable/elixir/Kernel.SpecialForms.html#%3C%3C%3E%3E/1

**Comment by bjhaid** [comment]
Not arguing the pattern matching, I meant not all the changes here, sorry I wasn't explicit

**Comment by dantswain** [comment]
Oh no worries :)  Can you revert the stuff around the pattern matching?  I'd prefer not to merge it like this.  We can wait a day or two for a fix on credo, though I hate leaving stuff open for long.

**Pull request merged**
