### PR TITLE
Release 0.13.0

### LINKED ISSUE #466: Create a new release with recent changes?
It's been quite a while since 0.12.1 was released and there seem to have been a couple of changes merged to the main branch (https://github.com/kafkaex/kafka_ex/pull/414 in particular). Is there any chance we could get a new `0.13.x` release for these changes? Longer term, what should expectations be around release cadence?

### PR DESCRIPTION
**Pull request by jbruggem**
Releases version 0.13.0

Closes #466

### CODE REVIEW

**Comment by jbruggem** [comment]
@dantswain @bjhaid @joshuawscott anything else that must be done to make a release ?

I suppose that once it's done, one of you has the ability to update `hex.pm` ?

**Review by joshuawscott — APPROVED** [review]

**Comment by Argonus** [comment]
@joshuawscott @jbruggem 
 Any chances to push this?

**Comment by Argonus** [comment]
@joshuawscott @dantswain Any updates?

**Comment by joshuawscott** [comment]
> @joshuawscott thanks ! Do we need a tag or something for this to happen ? Are you sure it's automatic ?

@jbruggem It's not automatic, but tagging does happen when you create a release and have it autogenerate the release notes.

When you get a chance can you re-push so that the CI checks will run again?

**Comment by jbruggem** [comment]
@joshuawscott should we merge then ?

**Pull request merged**
