### PR TITLE
README updates

### PR DESCRIPTION
**Pull request by dantswain**
* Add various badges
* Make the build badge link to the build
* Add language re: contribution and Slack channel

### CODE REVIEW

**Comment by bjhaid** [comment]
while making this changes, can we also add the `hex` badge and the `hexdocs` badge

**Comment by dantswain** [comment]
Will do.  I mostly opened the PR because I wanted to test the integration.  I was also going to add some info about the Slack channel.

**Comment by bjhaid** [comment]
:+1:

**Comment by bjhaid** [comment]
:ship: :it:

**Pull request merged**
