### PR TITLE
Test against multiple versions of Elixir and OTP

### PR DESCRIPTION
**Pull request by dantswain**
Re #101

### CODE REVIEW

**Comment by dantswain** [comment]
@bjhaid A few thoughts I had on this: 

1) OTP 17.4 had a bug that would cause segfaults in the network client - I have already run afoul of this in production.  I thought it would clear up the segfaults we were seeing in the test suite if we specified 17.5 (where the segfault was fixed was fixed), but It doesn't :/  You may be right on it being related to docker.

2) OTP 18.3 is not yet supported by Travis

3) A potential downside of this is that we have a lot of spurious test failures and this will increase the probability that any given build will fail :/

**Comment by bjhaid** [comment]
I sincerely will not pin against OTP versions, I will just list elixir versions, since elixir gradually drops support for older OTP versions

**Comment by dantswain** [comment]
I have run afoul of that as well :/  Is there any way to tell Travis to use certain combinations?  The reason I wanted to test against different versions of OTP is that I have seen at least two bugs that were specifically related to which version of OTP I'm using :(

**Comment by bjhaid** [comment]
https://docs.travis-ci.com/user/customizing-the-build/#Build-Matrix ?

**Comment by bjhaid** [comment]
so something like:

```yaml
matrix:
  exclude:
    - elixir: 1.0.4
    - otp_version: 18.2.1
```

**Comment by dantswain** [comment]
I like that.  Probably be a bit later today before I can get to it.

**Comment by dantswain** [comment]
@bjhaid Check this out.  I did end up having to restart one of the builds.

**Comment by bjhaid** [comment]
:+1: :shipit:

**Pull request merged**
